version: '3.8'

services:
  api:
    build: .
    container_name: stock_advisory_api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      # - influxdb
    networks:
      - stock_advisory_network
    restart: unless-stopped

  # postgres:
  #   image: postgres:14
  #   container_name: stock_advisory_postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER:-postgres}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  #     - POSTGRES_DB=${POSTGRES_DB:-stock_advisory}
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - stock_advisory_network
  #   restart: unless-stopped

  # redis:
  #   image: redis:7
  #   container_name: stock_advisory_redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - stock_advisory_network
  #   restart: unless-stopped

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: stock_advisory_pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@admin.com}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - stock_advisory_network
  #   restart: unless-stopped


# volumes:
#   postgres_data:

networks:
  stock_advisory_network: